### ISSUE TITLE
GUI not properly scaled

### ISSUE THREAD

**Issue by noetherianXD** [Alexdoru/MegaWallsEnhancements#27]
MegaWallsEnhancements v2.8
Video Settings - GUI Sacle : 4x (In fact, the mwen GUI remians the same whatever I set this setting to)
All mwen GUIs appears to be too small for my screen

**Comment by Alexdoru** [comment]
The gui scale for the config menus is forced to normal or even small if all the buttons can't fit within the screen

**Comment by Alexdoru** [comment]
Do you have a really high resolution screen ? Could you show me a screenshot of what the menu looks like for you ?

**Comment by noetherianXD** [comment]
![mwen gui](https://user-images.githubusercontent.com/96465019/205914412-33abb12f-367e-4b09-96b7-dbbc80a39a5f.png)

**Comment by noetherianXD** [comment]
It was normal before you adjust the config menu
and my screen resolution is 2560*1440

**Comment by Alexdoru** [comment]
should be fixed now
