### ISSUE TITLE
Final Kill Counter is bugged right now.

### ISSUE THREAD

**Issue by HSatt** [Alexdoru/MegaWallsEnhancements#33]
Hypixel added new kill messages(check the image below), so kills by those who use it wont be added to fk counter. 
![image](https://user-images.githubusercontent.com/44027343/230294553-f6c1d075-75cd-4fcc-832d-2b3a3bea2566.png)

**Comment by Alexdoru** [comment]
I know, I fixed it already but I am waiting for the cow class to get nerfed to release an update. It should be out within 2 weeks
