### ISSUE TITLE
The HUD element showing ping, miss rate, damage rate and APS keeps overlaying over compass HUD and ability HUD

### ISSUE THREAD

**Issue by jorgedomingues2003** [Alexdoru/MegaWallsEnhancements#37]
![2023-07-21_14 47 18](https://github.com/Alexdoru/MegaWallsEnhancements/assets/77934701/08cd6e76-f9fd-4390-aabe-942593327983)
![2023-07-21_14 47 16](https://github.com/Alexdoru/MegaWallsEnhancements/assets/77934701/e254d1a2-229b-4174-8cfb-cd6997d7d603)

**Comment by Alexdoru** [comment]
This has nothing to do with my mod, the informations about ping and stuff is from a Hypixel command
