### ISSUE TITLE
Suggestion: Auto FKs Reply

### ISSUE THREAD

**Issue by William071802** [Alexdoru/MegaWallsEnhancements#39]
Function: 
When another player (on same team) sends "Fks?", have option to automatically reply with the FK counts

Potential Issue: 
Multiple MWEnhancement clients respond at same time
Solution:
Wait random time up to 5 seconds after receipt to send reply, if another client sends first then cancel

**Comment by Alexdoru** [comment]
No, I don't want to make automated chat macros that make you send automated chat messages
