### ISSUE TITLE
Can the author make your MOD support Chinese?

### ISSUE THREAD

**Issue by mengzhu3261** [Alexdoru/MegaWallsEnhancements#40]
@Alexdoru  I like your MOD, it is very practical, but every time you have to switch to English to use it, can you add Chinese support, pls

**Comment by Alexdoru** [comment]
I can't I don't speak Chinese

**Comment by FlyModeZ** [comment]
maybe he mean the matching pattern? (of killing messages etc, i dont play mw)
it also would be achieved by custom matching patterns? like language files
