### ISSUE TITLE
crashing after newest update

### ISSUE THREAD

**Issue by fortXIV** [Alexdoru/MegaWallsEnhancements#41]
started crashing 24/7 after the new update - im certain its this mod because when i unloaded i stopped crashing. https://mclo.gs/PIJMZ2e

**Comment by Alexdoru** [comment]
I don't know what in my mod could be causing this error, it is probably a conflict with another one of your mods, could you try to start your game with just mega walls enhancements and then add the other mods one by one to see which one causes the conflict ?

**Comment by fortXIV** [comment]
Seems like you may have fixed the issue!

Would be nice if it automatically disabled "NoCheaters" if you're either on a server that isn't hypixel or a server that is 1.7.x compatible. On minemen some people flag killaura because they eat something while breaking a block, which you can on 1.7 but not 1.8+ (assume thats why anyways?)

**Comment by Alexdoru** [comment]
> Would be nice if it automatically disabled "NoCheaters" if you're either on a server that isn't hypixel or a server that is 1.7.x compatible. On minemen some people flag killaura because they eat something while breaking a block, which you can on 1.7 but not 1.8+ (assume thats why anyways?)

I will change this flag so it doesn't false flag players that punch while eating
