### ISSUE TITLE
Display Version Number

### ISSUE THREAD

**Issue by William0216** [Alexdoru/MegaWallsEnhancements#42]
It would be helpful if when running /mwe command, the current version number was displayed somewhere on screen.

**Comment by Alexdoru** [comment]
In the pause menu you can click the "mod list" button and select mega walls enhancements to see the current version you have installed 
![image](https://github.com/Alexdoru/MegaWallsEnhancements/assets/57050655/0e0537af-d10c-4d76-851a-44fb59b66cfc)
