### ISSUE TITLE
KillAura (A) Creates Yellow Flag

### ISSUE THREAD

**Issue by William0216** [Alexdoru/MegaWallsEnhancements#43]
The anticheat detected KillAura (A) and did the autoreport, however in TAB it shows yellow (I do not believe I've ever reported this player manually) but MWE did autoreport, I checked the last sent messages to confirm and the green report submitted text was also printed in chat. The same player later changed to red triangle when they flagged NoSlowDown and it did not attempt to re-report
![MW1](https://github.com/Alexdoru/MegaWallsEnhancements/assets/32989615/89f00ad7-cc8a-4464-93f8-8793354aae13)
![MW2](https://github.com/Alexdoru/MegaWallsEnhancements/assets/32989615/8b2761a3-e50c-4681-8b79-e1732dda12af)
![MW3](https://github.com/Alexdoru/MegaWallsEnhancements/assets/32989615/5f181655-58d4-4e54-a4cf-ba175d47e81d)

**Comment by Alexdoru** [comment]
What's the problem ?

**Comment by William0216** [comment]
When a hacker is flagged by the hackerdetecter the triangle turns Red. When manually reported without the hackerdetector flag it turns Yellow. Unless I'm misunderstanding something?

**Comment by Alexdoru** [comment]
The color of the iron depends of the type of hack, not if it was flagged by the hacker detector.
It turns red for the following : bhop, autoblock, fastbreak, noslowdown, scaffold.
