### ISSUE TITLE
Compatibility with labymod

### ISSUE THREAD

**Issue by Luciousdev** [Alexdoru/MegaWallsEnhancements#50]
I know that compatibility with labymod is not set as a feature, but I have a labymod install with forge and when I put the mod in there I get some errors and the game crashes (happens after joining a server/world).

I am aware that some mods just don't work with labymod, but it would be nice since I always use it for pvp etc and have a lot of presets.

I will attach the hastebin with the error as well.

https://paste.labymod.net/afagoxemobucarumecip 
[afagoxemobucarumecip.txt](https://github.com/user-attachments/files/16119881/afagoxemobucarumecip.txt)

**Comment by Alexdoru** [comment]
There's many more errors than just my mod in the crash report.
It looks like labymod is intentionally not respecting the deobfuscation process of minecraft set by forge and that breaks every class transformer in my mod.
I'm won't fix that, if labymod decides to break forge, it's their problem
